apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRSktYWkdpKzEvY0gwemp2cVpOZ1UxREFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGN4TVRFeE5Ua3hNRm9YRFRNMU1EY3dPVEV4TlRreApNRm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTk5TaExIaWxpRi9LWmF4YjkwaVJla1lHd1VMMmMxZk5DQ0xmUHNqYzlZYmNxUHduS0hiUjNPRnZITTQKRlBJK2t3TkdwNHBZY3M0NllscDJmVy9jdUdpallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVUzQ2piYW1SMzVWeFlYWk1LTENwS054b3lBSDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVUUrVXFVK0kKZHRhRzlsNlZvTkVnK3ZCbW9aL1Y2SlVrWGhkdmwxcGpqZVVDSVFDelJPSHdSN3RnRGV5T3NDYnA0K1JTOFJpegpMZ0dJRy9sRlUyaHRBcnhoa0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://172.15.110.10:6443
  name: debug-cluster
contexts:
- context:
    cluster: debug-cluster
    namespace: default
    user: admin@debug-cluster
  name: admin@debug-cluster
current-context: admin@debug-cluster
kind: Config
preferences: {}
users:
- name: admin@debug-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVN1Z0F3SUJBZ0lSQUo4V2RPbnZibHBlUmx2Uk1YcksyQ0V3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV5TURZeU1ERXdOVFphRncweU5qRXlNRFl5TURFeApNRFphTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk9DVVZOTEdHV25zTGFuUVhab296R3NDdnFhdU9kR2EKMHRBUThSdTZ0SCtSeFFvbkVMRzB2SjhQb2MvcDFhVjZjdUxaTFR0UWZPVUZoMTkyS3R0a2t0aWpTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlRjCktOdHFaSGZsWEZoZGt3b3NLa28zR2pJQWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQXJLSjR0d1FZTzhGWkwKQ2Nsa25nR0FWbUxjazRLRkUrWFpiQmZHaHlMM0lRSWhBTHZOOUJOZ3pxV2tWcWNYd013UDc5TGtqWVFTd29lZApwdEZ0d0JEU3ZIMmsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBxNlFjaWY1dkZ5YmtQL0FnQ1VFbStOU3N6TnU2UTR3c3lnMHVtVzFnQXBvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNEpSVTBzWVphZXd0cWRCZG1pak1hd0srcHE0NTBaclMwQkR4RzdxMGY1SEZDaWNRc2JTOApudytoeituVnBYcHk0dGt0TzFCODVRV0hYM1lxMjJTUzJBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
